apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  serviceAccountName: cart
  containers:
    - name: test
      image: 739561048503.dkr.ecr.us-east-1.amazonaws.com/schema-loader:2.0.3
      #command: [ "tail", "-f", "/]
      args: [ "mongo", "catalogue" ]
      env:
        - name: env
          value: prod
       
